Feature/moretests
samply/TransFAIR pull request #15
Opened 2022-12-24 21:28 UTC by enola-dkfz

2022-12-27 06:52 UTC, patrickskowronekdkfz requested changes
Needs some small improvements, but overall it is looking good.

2022-12-27 06:52 UTC, patrickskowronekdkfz commented on src/main/java/de/samply/transfair/converters/TemperatureConverter.java
> +      codeableConcept.getCodingFirstRep().setSystem("https://fhir.bbmri.de/CodeSystem/StorageTemperature").setCode("temperature2to10");
Please use a constant for the URL

2022-12-27 06:52 UTC, patrickskowronekdkfz commented on src/main/java/de/samply/transfair/resources/SpecimenMapping.java
> +    // Storage temperature is an extension of the collection
The collection doesn't have an extension temperutre. It has blood fusions extensions, which isn't a field on the bbmri.de side.

2022-12-27 06:52 UTC, patrickskowronekdkfz commented on src/test/java/de/samply/transfair/JsonUtils.java
> +    log.info(actualAsJson);
Please don't log the json.

2022-12-27 06:52 UTC, patrickskowronekdkfz commented on src/test/java/de/samply/transfair/resources/SpecimenMappingTest.java
> +    specimenMiiForComparing = new Specimen();
fastingStatus is missing.

2022-12-27 06:52 UTC, patrickskowronekdkfz commented on src/test/java/de/samply/transfair/resources/SpecimenMappingTest.java
> +    specimenBbmriForConverting = new Specimen();
fastingStatus is missing.

2022-12-27 16:23 UTC, enola-dkfz commented on src/test/java/de/samply/transfair/JsonUtils.java
> +    log.info(actualAsJson);
done

2022-12-27 16:23 UTC, enola-dkfz commented on src/test/java/de/samply/transfair/resources/SpecimenMappingTest.java
> +    specimenMiiForComparing = new Specimen();
done

2022-12-27 16:24 UTC, enola-dkfz commented on src/test/java/de/samply/transfair/resources/SpecimenMappingTest.java
> +    specimenBbmriForConverting = new Specimen();
done

2022-12-28 06:27 UTC, patrickskowronekdkfz approved these changes

2022-12-28 06:27 UTC, patrickskowronekdkfz commented on src/test/java/de/samply/transfair/converters/TemperatureConverterTest.java
> +import static org.junit.jupiter.api.Assertions.assertNull;;
One ";" too much

2022-12-28 06:29 UTC, merged