feat: add CI
samply/transFAIR pull request #3
Opened 2024-12-02 14:01 UTC by Threated

Just the boilerplate we have in the other projects as well. I did not add the dockerhub readme sync action yet because I dont know if docker hub actually supports rendering org files

2024-12-18 16:15 UTC, Threated commented on dev/test
> +  export EXCHANGE_ID_SYSTEM="SESSION_ID"
Is it correct that I set `PROJECT_ID_SYSTEM` to `SESSION_ID`? It was not set in your flake and is required for the ttp config without which the test did not pass.

2024-12-20 13:46 UTC, Threated commented
It finally passed with this branch of our rust CI https://github.com/samply/github-workflows/pull/40.
I will now revert this branch to use the main branch of the CI so you can merge it when you merged the other PR.
When you merge this can you click the rebase and merge option so the history looks nicer 🙏

2024-12-20 13:53 UTC, torbrenner requested changes

2024-12-20 13:53 UTC, torbrenner commented on dev/test
> +  export EXCHANGE_ID_SYSTEM="SESSION_ID"
No, you need to set it to "PROJECT_1_ID". I usually set it via commandline parameter but in ci the Environment Approach is totally fine.

2024-12-20 13:53 UTC, torbrenner commented on docker-compose.yml
> +      ML_LOG_LEVEL: "${ML_LOG_LEVEL:-debug}"
I would set the default of `ML_LOG_LEVEL` to `info`. But good idea to add it to the docker-compose file.

2024-12-20 14:01 UTC, Threated commented
Done

2025-01-07 09:52 UTC, torbrenner approved these changes

2025-01-07 11:25 UTC, merged