Simple improvements (for a developer) to run routine-connector.
samply/transFAIR pull request #5
Opened 2024-12-05 14:15 UTC by mmwaikar

Use dotenv crate to read from .env file.
Use pretty_assertions create to highlight where a test has failed.
Add an example-dotenv file (from where the key-value pairs can be copied)
Improve tests (call unwrap only if the result is ok).

2024-12-06 07:27 UTC, torbrenner approved these changes

2024-12-06 08:23 UTC, Threated requested changes

2024-12-06 08:23 UTC, Threated commented on Cargo.toml
> +dotenv = "0.15.0"
This crate has not seen updates in 4 years the maintained version of it is https://crates.io/crates/dotenvy

2024-12-06 08:23 UTC, Threated commented on src/main.rs
> +        assert_eq!(response_result.is_ok(), true, "POST response (from /requests) was not OK");
I dont really get how this improves the code. Unwraping/panicing in tests is totally fine. This assert will just discard the actual error message. If you want to add a more descriptive error message you could use `Result::expect`.

2024-12-06 08:23 UTC, Threated commented on src/main.rs
> +        let response = response_result.unwrap();
Same as above. Also while you are at it you can remove the dbg macro

2024-12-10 12:39 UTC, mmwaikar commented on Cargo.toml
> +dotenv = "0.15.0"
Done.

2024-12-12 12:26 UTC, mmwaikar commented on src/main.rs
> +        assert_eq!(response_result.is_ok(), true, "POST response (from /requests) was not OK");
Done.

2024-12-12 12:28 UTC, mmwaikar commented on src/main.rs
> +        let response = response_result.unwrap();
Done, removed dbg macro.

2024-12-18 08:59 UTC, Threated commented
Maybe we can avoid dotenv entirely by using this https://doc.rust-lang.org/nightly/cargo/reference/config.html#env

2024-12-18 14:34 UTC, Threated requested changes
Also can you commit the .cargo/config.toml

2024-12-18 14:34 UTC, Threated commented on example-dotenv.md
Do we need this file now that we don't use dotenvy anymore

2024-12-18 14:34 UTC, Threated commented on src/main.rs
> +        dbg!(env::var("no_proxy").is_ok());
`reqwest` uses the no proxy env var by default. Besides that this line only prints whether `no_proxy` is set which is not that useful I feel like

2024-12-18 14:34 UTC, Threated commented on src/main.rs
> +    // #[traced_test]
```suggestion
```

2024-12-18 15:08 UTC, mmwaikar commented on example-dotenv.md
Deleted.

2024-12-18 15:11 UTC, mmwaikar commented on src/main.rs
> +        dbg!(env::var("no_proxy").is_ok());
Deleted.

2024-12-18 15:14 UTC, mmwaikar commented on src/main.rs
> +    // #[traced_test]
Deleted.

2024-12-18 15:21 UTC, merged